require(knitr)
require(markdown)
# setwd("~/GitHub Project")
setwd("~/Desktop/DataScience/C4W4/Project")
knit("run_analysis.Rmd", encoding="ISO8859-1")
markdownToHTML("run_analysis.md", "run_analysis.html")
